force-app/main/default/objects/Professional_Achievement__c/Professional_Achievement__c.object-meta.xml
<CustomObject>
    <description>Professional Achievement [ Academic Education | Professional Certification | Honors Award | Skill Learning | Resume Profile | Identity Logo  ]</description>
    <label>Professional Achievement</label>
    <nameField>
        <displayFormat>CRD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Achievement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Professional_Achievement__c/fields/Achievement_Name__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Name__c</fullName>
    <label>Achievement Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Professional_Achievement__c/fields/Available_URL__c.field-meta.xml
<CustomField>
    <fullName>Available_URL__c</fullName>
    <label>Available URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Professional_Achievement__c/fields/Extra_Data__c.field-meta.xml
<CustomField>
    <fullName>Extra_Data__c</fullName>
    <label>Extra Data</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Professional_Achievement__c/fields/Hashtags__c.field-meta.xml
<CustomField>
    <fullName>Hashtags__c</fullName>
    <label>Hashtags</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Professional_Achievement__c/fields/Issued_By__c.field-meta.xml
<CustomField>
    <fullName>Issued_By__c</fullName>
    <label>Issued By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Professional_Achievement__c/fields/Techstack__c.field-meta.xml
<CustomField>
    <fullName>Techstack__c</fullName>
    <label>Techstack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/Rushikesh_Information__mdt.object-meta.xml
<CustomObject>
    <label>Rushikesh Information</label>
    <pluralLabel>Rushikesh Information</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/About_HTML__c.field-meta.xml
<CustomField>
    <fullName>About_HTML__c</fullName>
    <label>About HTML</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <label>Contact Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Current_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Company_Name__c</fullName>
    <label>Current Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <label>Email ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Github_ID__c.field-meta.xml
<CustomField>
    <fullName>Github_ID__c</fullName>
    <label>Github ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Github_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_URL__c</fullName>
    <label>Github URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <label>Post</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Secondary_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_ID__c</fullName>
    <label>Secondary Email ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Sub_Post__c.field-meta.xml
<CustomField>
    <fullName>Sub_Post__c</fullName>
    <label>Sub Post</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rushikesh_Information__mdt/fields/Trialhead_URL__c.field-meta.xml
<CustomField>
    <fullName>Trialhead_URL__c</fullName>
    <label>Trialhead URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SVG_Icon__c/SVG_Icon__c.object-meta.xml
<CustomObject>
    <description>In this object I just store the SVG code and SVG label for HTML an JS</description>
    <label>SVG Icon</label>
    <nameField>
        <label>SVG Icon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SVG Icon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SVG_Icon__c/fields/Menu_Rank__c.field-meta.xml
<CustomField>
    <fullName>Menu_Rank__c</fullName>
    <label>Menu Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVG_Icon__c/fields/SVG_Code__c.field-meta.xml
<CustomField>
    <fullName>SVG_Code__c</fullName>
    <label>SVG Code</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVG_Icon__c/fields/SVG_Functional_Context__c.field-meta.xml
<CustomField>
    <fullName>SVG_Functional_Context__c</fullName>
    <label>SVG Functional Context</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Menu</fullName>
            </value>
            <value>
                <fullName>Navigation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVG_Icon__c/fields/SVG_Label__c.field-meta.xml
<CustomField>
    <fullName>SVG_Label__c</fullName>
    <label>SVG Label</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Contact__c/User_Contact__c.object-meta.xml
<CustomObject>
    <description>User try to connect with you</description>
    <label>User Contact</label>
    <nameField>
        <label>User Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Contact__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Contact__c/fields/Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Id__c</fullName>
    <label>Tracking Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Visitor_Tracking__c/User_Visitor_Tracking__c.object-meta.xml
<CustomObject>
    <description>Any visiter details analysis report here</description>
    <label>User Visitor Tracking</label>
    <nameField>
        <displayFormat>UVT-{0000}</displayFormat>
        <label>User Visit Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Visitor Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Visitor_Tracking__c/fields/Clicks__c.field-meta.xml
<CustomField>
    <fullName>Clicks__c</fullName>
    <label>Clicks</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User_Visitor_Tracking__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User_Visitor_Tracking__c/fields/Ip_Address__c.field-meta.xml
<CustomField>
    <fullName>Ip_Address__c</fullName>
    <description>I will store the ip or else latest UVT IP-AutoNumber</description>
    <label>Ip Address</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Visitor_Tracking__c/fields/Navigation__c.field-meta.xml
<CustomField>
    <fullName>Navigation__c</fullName>
    <label>Navigation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PortfolioMainClass.cls
public without sharing class PortfolioMainClass {

    @AuraEnabled
    public static String createUserContact(Id lwcId, String jsonString) {
        try {
            Map<String, Object> data = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
            User_Contact__c newContact = new User_Contact__c();
            newContact.Name = (String) data.get('name');
            newContact.Email__c = (String) data.get('email');
            newContact.Company__c = (String) data.get('company');
            newContact.Phone__c = (String) data.get('phone');
            newContact.Subject__c = (String) data.get('subject');
            newContact.Message__c = (String) data.get('message');
            newContact.Tracking_Id__c = lwcId; 
            insert newContact;
            return 'Record Created Successfully: ' + newContact.Id;
        } catch (Exception e) {
            throw new AuraHandledException('Error processing request: ' + e.getMessage());
        }
    }

     @AuraEnabled
    public static void updateVisitorTracking(Id recordId, String trackingJson) {
        if (recordId == null) {
            throw new AuraHandledException('Record Id is required.');
        }
        if (String.isBlank(trackingJson)) {
            throw new AuraHandledException('Tracking JSON cannot be empty.');
        }
        Map<String, Object> parsedData =
            (Map<String, Object>) JSON.deserializeUntyped(trackingJson);
        String engagementJson = parsedData.containsKey('engagement')
            ? JSON.serialize(parsedData.get('engagement'))
            : null;
        String clicksJson = parsedData.containsKey('clicks')
            ? JSON.serialize(parsedData.get('clicks'))
            : null;
        String navigationJson = parsedData.containsKey('nav')
            ? JSON.serialize(parsedData.get('nav'))
            : null;
        User_Visitor_Tracking__c recordToUpdate = new User_Visitor_Tracking__c(
            Id = recordId,
            Engagement__c = engagementJson,
            Clicks__c = clicksJson,
            Navigation__c = navigationJson
        );
        update recordToUpdate;
    }

    @AuraEnabled
    public static String getLiveViewCount() {
        List<User_Visitor_Tracking__c> globalLatest = [SELECT Name FROM User_Visitor_Tracking__c 
                                       ORDER BY CreatedDate DESC LIMIT 1];
                                       String autoNumber = globalLatest[0]?.Name;
        String numericPart = autoNumber?.replaceAll('[^0-9]', '');
        Integer latestCount = Integer.valueOf(numericPart);
        Integer finalCount = latestCount + 1;
        return String.valueOf(finalCount);
    }

    @AuraEnabled
    public static Map<String, Object> getOrRegisterIP() {
        List<User_Visitor_Tracking__c> globalLatest = [SELECT Name FROM User_Visitor_Tracking__c 
                                       ORDER BY CreatedDate DESC LIMIT 1];
        String autoNumber = globalLatest[0]?.Name;
        String numericPart = autoNumber?.replaceAll('[^0-9]', '');
        Integer latestCount = Integer.valueOf(numericPart);
        Map<String, Object> response = new Map<String, Object>();
        String recordId = null;
                User_Visitor_Tracking__c newLog = new User_Visitor_Tracking__c(IP_Address__c = '0.0.0.'+(latestCount+1));
                insert newLog;
                recordId = newLog.Id;
                Integer finalCount = latestCount + 1;
        response.put('recordId', recordId);
        response.put('countValue', String.valueOf(finalCount));
        return response;
    }

    @AuraEnabled(cacheable=true)
    public static Rushikesh_Information__mdt getRushikeshMdtInfo() {
        try {
            return [ SELECT name__c, full_name__c, post__c, sub_post__c, 
                github_id__c, github_url__c, email_id__c, secondary_email_id__c, trialhead_url__c, linkedin_url__c, 
                current_company_name__c, contact_number__c, about__c, about_html__c 
                FROM rushikesh_information__mdt WHERE Name__c = 'Rushikesh Kale' 
                LIMIT 1 ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving metadata: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, String> getSvgIconsByName(String iconNames) {
        Map<String, String> iconMap = new Map<String, String>(); 
        if (String.isBlank(iconNames)) {
            return iconMap;
        }
        List<String> nameList = iconNames.split(';');
        try {
            for (SVG_Icon__c icon : [ SELECT Name, SVG_Code__c FROM SVG_Icon__c WHERE Name IN :nameList and IsActive__c = true ]) {
                iconMap.put(icon.Name, icon.SVG_Code__c);
            }
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching SVG icons: ' + e.getMessage());
        }
        return iconMap;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, List<SVG_Icon__c>> getIconsByContext() {
        Map<String, List<SVG_Icon__c>> groupedMap = new Map<String, List<SVG_Icon__c>>();
        try {
            List<SVG_Icon__c> allIcons = [
                SELECT Name, SVG_Label__c, SVG_Functional_Context__c, Menu_Rank__c, SVG_Code__c 
                FROM SVG_Icon__c 
                WHERE SVG_Functional_Context__c != null and IsActive__c = true
                ORDER BY Menu_Rank__c
            ];
            for (SVG_Icon__c icon : allIcons) {
                List<String> contexts = icon.SVG_Functional_Context__c.split(';');
                for (String context : contexts) {
                    if (!groupedMap.containsKey(context)) {
                        groupedMap.put(context, new List<SVG_Icon__c>());
                    }
                    groupedMap.get(context).add(icon);
                }
            }
        } catch (Exception e) {
            throw new AuraHandledException('Error processing SVG data: ' + e.getMessage());
        }
        return groupedMap;
    }

    public class AchievementWrapper {
        @AuraEnabled public String name {get;set;}
        @AuraEnabled public String logoBase64 {get;set;}
        @AuraEnabled public String certBase64 {get;set;}
        @AuraEnabled public String description {get;set;}
        @AuraEnabled public Date sdate {get;set;}

        public AchievementWrapper(String name) {
            this.name = name;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<AchievementWrapper> getCertificateDetails() {
        List<Professional_Achievement__c> records = [
            SELECT Id, Achievement_Name__c, RecordType.Name , Description__c, Start_Date__c, Hashtags__c, Techstack__c
            FROM Professional_Achievement__c
            WHERE IsActive__c = true
            AND (RecordType.Name = 'Professional Certification')
            ORDER BY Start_Date__c DESC
        ];
        if(records.isEmpty()) {
            return new List<AchievementWrapper>();
        }
        List<AchievementWrapper> wrapperList = new List<AchievementWrapper>();
        for(Professional_Achievement__c pa : records) {
            AchievementWrapper wrap = new AchievementWrapper(pa.Achievement_Name__c);
            wrap.description = pa.Description__c;
            wrap.sdate = pa.Start_Date__c;
            wrap.certBase64 = pa.Hashtags__c;
            wrap.logoBase64 = pa.Techstack__c;
            wrapperList.add(wrap);
        }
        return wrapperList;
    }

    public class EducationWrapper {
        @AuraEnabled public String degree {get;set;}
        @AuraEnabled public String institution {get;set;}
        @AuraEnabled public String duration {get;set;}
        @AuraEnabled public String grade {get;set;}
        @AuraEnabled public String description {get;set;}
        @AuraEnabled public String imageUrl {get;set;}
        @AuraEnabled public String location {get;set;}
        @AuraEnabled public String siteUrl {get;set;}
        @AuraEnabled public Boolean isPrimary {get;set;}
    }

    @AuraEnabled(cacheable=true)
    public static List<EducationWrapper> getEducationDetails() {
        List<Professional_Achievement__c> records = [
            SELECT Id, Achievement_Name__c, RecordType.Name, Description__c, Techstack__c, Issued_By__c, Hashtags__c, Available_URL__c, Extra_Data__c
            FROM Professional_Achievement__c
            WHERE IsActive__c = true
            AND RecordType.Name = 'Academic Education'
            ORDER BY Start_Date__c DESC
        ];
        if(records.isEmpty()) {
            return new List<EducationWrapper>();
        }
        List<EducationWrapper> wrapperList = new List<EducationWrapper>();
        for(Professional_Achievement__c pa : records) {
            EducationWrapper wrap = new EducationWrapper();
            wrap.degree = pa.Achievement_Name__c;
            wrap.institution = pa.Issued_By__c;
            wrap.duration = pa.Techstack__c;
            wrap.grade = pa.Hashtags__c;
            wrap.description = pa.Description__c;
            wrap.location = 'Pune, Maharashtra, India';
            wrap.siteUrl = pa.Available_URL__c;
            wrap.isPrimary = true;
            wrap.imageUrl = pa.Extra_Data__c;
            wrapperList.add(wrap);
        }
        return wrapperList;
    }

    @AuraEnabled(cacheable=true)
    public static List<EducationWrapper> getRewardAndRecognation() {
        List<Professional_Achievement__c> records = [
            SELECT Id, Achievement_Name__c, RecordType.Name, Description__c, Techstack__c, Issued_By__c, Hashtags__c, Available_URL__c, Extra_Data__c
            FROM Professional_Achievement__c
            WHERE IsActive__c = true
            AND RecordType.Name = 'Honors Award'
            ORDER BY Start_Date__c DESC
        ];
        if(records.isEmpty()) {
            return new List<EducationWrapper>();
        }
        List<EducationWrapper> wrapperList = new List<EducationWrapper>();
        for(Professional_Achievement__c pa : records) {
            EducationWrapper wrap = new EducationWrapper();
            wrap.degree = pa.Achievement_Name__c;
            wrap.institution = pa.Issued_By__c;
            wrap.duration = pa.Techstack__c;
            wrap.grade = pa.Hashtags__c;
            wrap.description = pa.Description__c;
            wrap.location = 'Pune, Maharashtra, India';
            wrap.siteUrl = pa.Available_URL__c;
            wrap.isPrimary = true;
            wrap.imageUrl = pa.Extra_Data__c;
            wrapperList.add(wrap);
        }
        return wrapperList;
    }
}